# -*- coding: utf-8 -*-
"""de_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7E797FJT2Gfhhr9gYCxoOt5rM4wEO0B
"""

import streamlit as st
from transformers import pipeline

# ----------------------------------------------------
# 1. GA4 태그 삽입 함수 정의 (가장 먼저 실행되어야 함)
# ----------------------------------------------------
def inject_ga4_tag(tracking_id):
    """GA4 측정 ID를 사용하여 HTML 태그를 Streamlit 앱에 삽입합니다."""

    # 템플릿 리터럴을 사용하여 tracking_id를 동적으로 삽입
    ga4_script = f"""
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id={tracking_id}"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){{dataLayer.push(arguments);}}
          gtag('js', new Date());
          gtag('config', '{tracking_id}', {{
              'cookie_flags': 'secure;samesite=none'
          }});
        </script>
    """
    # Streamlit 앱의 최상단에 HTML을 삽입합니다.
    # 안전성 및 초기화를 위해 앱 실행의 맨 처음에 위치해야 합니다.
    st.markdown(ga4_script, unsafe_allow_html=True)


# ----------------------------------------------------
# 2. GA4 이벤트 전송 함수 정의
# ----------------------------------------------------
def send_ga4_event(event_name, event_params={}):
    """
    GA4 이벤트를 전송하는 JavaScript 코드를 Streamlit 앱에 삽입합니다.
    이 함수는 사용자 상호 작용(예: 버튼 클릭)이 있을 때 호출되어야 합니다.
    """
    # 이벤트 매개변수를 JSON 문자열로 변환
    params_json = str(event_params).replace("'", '"')

    # gtag('event', ...) 호출을 수행하는 JavaScript
    js_code = f"""
        <script>
            if (typeof gtag === 'function') {{
                gtag('event', '{event_name}', {params_json});
            }}
        </script>
    """
    # 이벤트를 전송하는 JavaScript를 페이지에 삽입
    # key를 사용하여 매번 재실행되도록 합니다.
    st.components.v1.html(js_code, height=0, width=0)

# GA4 태그 삽입 (앱의 맨 처음에 실행)
# G-BPJTDJ4BKF 대신 실제 측정 ID를 사용하세요.
inject_ga4_tag("G-BPJTDJ4BKF")


# 저장된 모델 경로 (Hugging Face Model Hub 사용)
MODEL_PATH = "ju03/Chatbot_Emotion-classification"

# 모델 로드 (앱이 로드될 때 한 번만 실행)
@st.cache_resource
def load_model():
    # 텍스트 분류 파이프라인 사용
    try:
        classifier = pipeline(
            "text-classification",
            model=MODEL_PATH,
            tokenizer=MODEL_PATH
        )
        return classifier
    except Exception as e:
        st.error(f"모델 로드 실패! 다음 라이브러리가 'requirements.txt'에 있는지 확인하세요: streamlit, transformers, torch (또는 tensorflow)")
        return None

classifier = load_model()

st.title('배달 앱 리뷰 감성 분류 봇 🤖')
st.write('파인튜닝된 KLUE/RoBERTa 모델로 리뷰를 긍정/부정 분류합니다.')

# 텍스트 영역 생성
review_text = st.text_area("리뷰를 여기에 입력하세요:", height=150, placeholder="예: '배달이 너무 빨랐고 음식이 정말 맛있었어요!'")

with st.expander("예시 리뷰 보기"):
    st.write("👍 긍정 예시: 사장님이 너무 친절하시고 서비스도 좋아서 다음에도 꼭 주문하고 싶어요!")
    st.write("👎 부정 예시: 주문한 메뉴가 잘못 왔고, 포장이 엉망이라 다 식어서 왔네요.")


if st.button('분류하기'):
    if not classifier:
        st.warning("모델이 로드되지 않아 분류를 진행할 수 없습니다.")
    elif review_text.strip() == "":
        st.warning("분류할 리뷰 텍스트를 입력해주세요.")
    else:
        # 진행률 표시줄
        with st.spinner('리뷰 분석 중...'):

            # 예측 수행
            result = classifier(review_text)[0]

        label = result['label']
        score = result['score']

        # 결과 매핑
        sentiment = '긍정 👍' if label == 'LABEL_1' else '부정 👎'

        # ----------------------------------------------------
        # 3. GA4 이벤트 전송 (분류 버튼 클릭 이벤트)
        # ----------------------------------------------------
        send_ga4_event(
            event_name="review_classified",
            event_params={
                "sentiment_label": sentiment,
                "confidence_score": f"{score:.2f}",
                "review_length": len(review_text)
            }
        )
        # ----------------------------------------------------

        st.success('✅ 분류 완료!')
        st.metric(label="분류 결과", value=sentiment)
        st.info(f"신뢰도: {score*100:.2f}%")